/* Generated by admin.html */
const CONFIG = {
  "name": "FAST TRASH LV",
  "shortName": "FAST TRASH LV",
  "logoEmoji": "🚛",
  "logo": "images/logo.svg",
  "showNameWithLogo": true,
  "siteUrl": "",
  "ogImage": "images/og-image.jpg",
  "priceRange": "$$",
  "openingHours": [
    "Mo-Fr 07:00-19:00",
    "Sa 08:00-17:00"
  ],
  "social": [
    {
      "name": "Facebook",
      "url": ""
    },
    {
      "name": "Instagram",
      "url": ""
    },
    {
      "name": "Google Business",
      "url": ""
    },
    {
      "name": "TikTok",
      "url": ""
    },
    {
      "name": "YouTube",
      "url": ""
    },
    {
      "name": "X",
      "url": ""
    }
  ],
  "formEndpoint": "",
  "tagline": "Fast • Affordable • Reliable Junk Removal",
  "intro": "Furniture, appliances, yard waste, construction debris. Our crew does the lifting, loading and sweeping up, and you get a flat price before we touch anything.",
  "phone": "(725)3106096",
  "email": "fasttrashlv@gmail.com",
  "addr": {
    "street": "",
    "city": "Las Vegas Valley",
    "region": "",
    "zip": "",
    "country": "US"
  },
  "serviceArea": "Serving Your City and a 30-mile radius",
  "areas": [
    "Your City",
    "Northside",
    "Riverview",
    "Oak Park",
    "Lakeshore",
    "Fairmont"
  ],
  "hours": [
    [
      "Monday to Friday",
      "7am to 7pm"
    ],
    [
      "Saturday",
      "8am to 5pm"
    ],
    [
      "Sunday",
      "Emergency pickups only"
    ]
  ],
  "accentLight": "#e84e11",
  "accentDark": "#e77408",
  "stats": [
    [
      "200+",
      "Jobs completed"
    ],
    [
      "60%",
      "Of loads donated or recycled"
    ],
    [
      "2 hr",
      "Typical arrival window"
    ],
    [
      "$2M",
      "Liability insurance"
    ]
  ],
  "services": [
    {
      "icon": "🛋️",
      "title": "Furniture & mattress removal",
      "desc": "Couches, beds, dressers, desks. We carry it out, you keep your floors clean."
    },
    {
      "icon": "🧊",
      "title": "Appliance hauling",
      "desc": "Fridges, washers, stoves and water heaters, disconnected and removed safely."
    },
    {
      "icon": "🏠",
      "title": "Estate & whole-home cleanouts",
      "desc": "Respectful, thorough clearing of homes, apartments, garages and storage units."
    },
    {
      "icon": "🧱",
      "title": "Construction & renovation debris",
      "desc": "Drywall, flooring, cabinets, lumber and tile after the remodel is done."
    },
    {
      "icon": "🌳",
      "title": "Yard waste & storm cleanup",
      "desc": "Branches, brush, fencing, old sheds and hot tubs."
    },
    {
      "icon": "🏢",
      "title": "Commercial & property managers",
      "desc": "Move-outs, office cleanouts and recurring pickups with invoicing."
    }
  ],
  "steps": [
    [
      "Book online or call",
      "Pick a window that works. Same-day slots are often open."
    ],
    [
      "Get a flat quote",
      "The crew walks the job and gives a firm price before any work starts."
    ],
    [
      "We load everything",
      "Say yes and we lift, load and sweep. You never move a thing."
    ],
    [
      "Responsible disposal",
      "We donate, recycle and only landfill what we have to."
    ]
  ],
  "tiers": [
    {
      "name": "Single item",
      "load": 0.0625,
      "price": 89,
      "desc": "One couch, mattress or appliance"
    },
    {
      "name": "Quarter truck",
      "load": 0.25,
      "price": 199,
      "desc": "A small room or garage corner"
    },
    {
      "name": "Half truck",
      "load": 0.5,
      "price": 349,
      "desc": "A bedroom or small renovation"
    },
    {
      "name": "Three-quarter",
      "load": 0.75,
      "price": 489,
      "desc": "Multi-room cleanup"
    },
    {
      "name": "Full truck",
      "load": 1,
      "price": 649,
      "desc": "Whole garage or estate cleanout"
    }
  ],
  "extras": [
    {
      "label": "Stairs or long carry",
      "price": 40
    },
    {
      "label": "Heavy items (piano, safe, hot tub)",
      "price": 75
    },
    {
      "label": "Same-day service",
      "price": 50
    }
  ],
  "estimateRange": 0.15,
  "accepted": [
    "Furniture",
    "Mattresses",
    "Appliances",
    "Electronics",
    "Yard debris",
    "Construction waste",
    "Carpet",
    "Clothing",
    "Exercise equipment"
  ],
  "notAccepted": [
    "Hazardous chemicals",
    "Paint and solvents",
    "Asbestos",
    "Medical waste",
    "Propane tanks",
    "Explosives"
  ],
  "testimonials": [
    {
      "q": "They showed up inside the window, quoted a price and stuck to it. The garage was empty in 40 minutes.",
      "n": "Dana R., Northside"
    },
    {
      "q": "Cleared my late mother's house over two days with real care. I can't recommend them enough.",
      "n": "Marcus T., Oak Park"
    },
    {
      "q": "We use HaulRight for every tenant move-out. Fast, fair and they send invoices.",
      "n": "Priya S., Property manager"
    }
  ],
  "faq": [
    [
      "How is pricing calculated?",
      "By the space your items take up in our truck, plus any extras. You get a flat quote on site before we start."
    ],
    [
      "Do I need to be home?",
      "Not for outdoor pickups. For indoor jobs, someone should be there to point out what goes."
    ],
    [
      "Do you donate or recycle?",
      "Yes. Usable items go to local charities and we recycle metal, cardboard and electronics wherever possible."
    ],
    [
      "Are you insured?",
      "Yes. We carry general liability and workers' compensation coverage."
    ],
    [
      "How soon can you come?",
      "Often the same day. Book online or call and we'll confirm a window."
    ]
  ],
  "seo": {
    "home": {
      "title": "Junk Removal & Hauling in Las Vegas Valley  | Las Vegas",
      "description": "Fast, affordable junk removal and hauling in Columbus, Ohio. Flat quotes, same-day pickup and responsible disposal. Call +16142182507."
    },
    "services": {
      "title": "Junk Removal Services in Las Vegas Valley  | Las Vegas",
      "description": "Furniture, appliance, yard waste, construction debris and whole-home cleanouts in Columbus. Insured crew, flat pricing. Call +17253106096."
    },
    "gallery": {
      "title": "Before and After Junk Removal Photos | {name}",
      "description": "See real junk removal jobs in {city}: garages, estates, yards and remodels cleared and hauled away. Get a free quote today."
    },
    "pricing": {
      "title": "Junk Removal Prices in {city} | {name}",
      "description": "Simple truck-load pricing for junk removal in {city}. Use our estimator for a price range, then get a flat quote before we start."
    },
    "contact": {
      "title": "Free Junk Removal Quote in {city} | {name}",
      "description": "Book junk removal in {city}, {region}. Request a free quote online or call {phone}. Same-day pickup often available."
    }
  },
  "gallery": [
    {
      "cat": "Garage",
      "title": "Two-car garage cleanout",
      "caption": "Cleared in 90 minutes. Six items donated.",
      "icons": "📦🧰🚲📦🛞",
      "before": "",
      "after": ""
    },
    {
      "cat": "Estate",
      "title": "Whole-home estate cleanout",
      "caption": "Two days, handled with care, usable items donated.",
      "icons": "🛋️🖼️📚🪑🧳",
      "before": "",
      "after": ""
    },
    {
      "cat": "Yard",
      "title": "Storm damage and brush",
      "caption": "Fallen limbs and an old fence, gone by lunch.",
      "icons": "🪵🌿🪵🌳🌿",
      "before": "",
      "after": ""
    },
    {
      "cat": "Renovation",
      "title": "Kitchen remodel debris",
      "caption": "Cabinets, tile and drywall hauled and sorted for recycling.",
      "icons": "🧱🚪🪟🧱🪚",
      "before": "",
      "after": ""
    },
    {
      "cat": "Appliances",
      "title": "Old appliances, one trip",
      "caption": "Fridge, washer and dryer disconnected and removed.",
      "icons": "🧊🧺🔥🧊",
      "before": "",
      "after": ""
    },
    {
      "cat": "Commercial",
      "title": "Office move-out",
      "caption": "Desks, chairs and cubicle walls cleared over a weekend.",
      "icons": "🪑🖥️🗄️🪑🖨️",
      "before": "",
      "after": ""
    }
  ],
  "about": "We started with one old pickup and a belief that hauling should be simple, honest and clean. Today we run a small fleet with a crew of background-checked, uniformed team members who treat your property like their own."
};
